"""Make a three-panel version of figures/energy_crowding.png for the article (crude price,
vol-targeted cosine similarity, binary crowding windows) by cropping the six stacked panels of
the full figure. The full figure stays as generated by commodity_crowding_analysis.py.
usage: python research/crop_energy_figure.py"""
from PIL import Image
import numpy as np

SRC = "figures/energy_crowding.png"; OUT = "figures/energy_crowding_3panel.png"
im = Image.open(SRC).convert("RGB"); a = np.asarray(im)
# panel boundaries: rows that are (almost) entirely white across the plotting width separate the panels
row_white = (a[:, a.shape[1] // 4: 3 * a.shape[1] // 4] > 245).all(axis=2).mean(axis=1)
inside = row_white < 0.98
# runs of non-white rows = panels (plus title/tick-label strips); keep the six tallest runs
runs = []; start = None
for i, v in enumerate(inside):
    if v and start is None: start = i
    if not v and start is not None: runs.append((start, i)); start = None
if start is not None: runs.append((start, len(inside)))
runs = sorted(sorted(runs, key=lambda r: r[1] - r[0], reverse=True)[:6])
assert len(runs) == 6, runs
pad = 12
keep = [0, 4, 5] # crude price, cosine similarity, binary crowding
pieces = [a[runs[k][0] + (2 if k == 0 else -pad): min(a.shape[0], runs[k][1] + pad), :, :] for k in keep] # panel 0: drop the figure title
# keep the x-axis tick labels that sit below the last panel
tail = a[runs[5][1]:, :, :]
out = np.concatenate(pieces[:2] + [np.concatenate([pieces[2], tail], axis=0)], axis=0)
Image.fromarray(out).save(OUT, dpi=(160, 160))
print("wrote", OUT, out.shape, "panel rows:", runs)
